jobs:
  queue_pipeline:
    docker:
      - image: cimg/base:current
    steps:
    - checkout
    - run: ./.scripts/do-exclusively --branch $CIRCLE_BRANCH
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo "aaa" && sleep 1m
  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo "bbbb"
workflows:
  version: 2
  build_and_test:
    jobs:
      - queue_pipeline
      - build:
          requires:
            - queue_pipeline
      - test:
          requires:
            - build
