jobs:
  build:
    docker:
      - image: cimg/base
    steps:
      - checkout
      - run: echo "aaa" && sleep 1m
  test:
    docker:
      - image: cimg/base
    steps:
      - checkout
      - run: echo "bbbb"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
